server:
  port: ${SERVER_PORT}

spring:
  application:
    name: mcp
  ai:
    mcp:
      server:
        name: amaliai-mcp-server
        type: SYNC
        transport: SSE
        capabilities:
          resource: false
          prompt: false
          tool: true
        resource-change-notification: false
        false-change-notification: false
        tool-change-notification: true
        request-timeout: 30s
        sse-endpoint: /sse

backend:
  api:
    url: ${BACKEND_API_URL}
    key: ${MCP_API_KEY}
  integrations:
    share-point:
      tenant-id: ${SHAREPOINT_TENANT_ID}